# CIS7026 - Business Process and Data Analysis

# Week 4 Numpy and Pandas

In the week 4 workshop, you will learn/revise the Numpy and Pandas. There are empty cells where you are required to do small tasks. Please, write below # line in those empty cells as # is used to comment code in Python. 
# Note
This course does not require intensive programming in Python. Therefore, we will not go deep in the programming but rather do a crash course during workshop sessions. So that you may get familiar with the basic concepts of Python programming with hands-on practice. 

You can always learn more in your own time with the Online resources provided in the Python Programing section at Moodle.

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python. Numpy is an important Data Science library. 

## Installation

Generally, Numpy is pre-installed in anaconda but if the following command doesn't work then you will need to install it by running this command in anaconda command prompt: 

    conda install numpy
    
## importing and using Numpy

In [1]:
# import numpy - import is generally used to add already installed Python packages. Here we want to import numpy 
import numpy as np 

# Numpy Arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.
## Creating NumPy Arrays

### From a Python List


In [2]:
#create a python list
my_list = [1,2,3]
# provide python list as input to np.array()
np.array(my_list)

array([1, 2, 3])

In [3]:
# create a nested list/matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods
### arange

Return evenly spaced values within a given interval.

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones
generate arrays of ones and zero

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random Numbers

create random number arrays

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(3)

array([0.36148307, 0.15307592, 0.71169475])

In [17]:
np.random.rand(3,3)

array([[0.83623321, 0.08838757, 0.22235227],
       [0.84927329, 0.1307674 , 0.08311066],
       [0.98493533, 0.50977101, 0.28979849]])

### randn

Return a sample (or samples) from the "standard normal" distribution.

In [19]:
np.random.randn(3)

array([-0.63181528, -0.12802257,  0.10729141])

In [20]:
np.random.randn(3,3)

array([[-0.37732834, -0.16076353, -1.31425049],
       [-0.01316843, -0.4436097 , -0.19841639],
       [ 1.37028466,  1.24475511,  0.58010303]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [22]:
np.random.randint(1,100)

68

In [23]:
np.random.randint(1,100,10)

array([49, 46, 17, 71,  9, 84, 87, 64, 93, 20])

## Array Attributes and Methods

In [24]:
a = np.arange(25)
ran= np.random.randint(0,50,10)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ran

array([27, 15,  6, 33,  2, 43, 49, 37, 45, 45])

## Reshape
Reshape the array

In [27]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [28]:
ran.max()

49

In [29]:
ran.argmax()

6

In [30]:
ran.min()

2

In [31]:
ran.argmin()

4

# NumPy Indexing and Selection
Select elements or group

In [33]:
#Creating sample array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Get a value at an index
arr[8]

8

In [36]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [37]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Indexing a 2D array (matrices)

In [45]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

#Show
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
#Indexing row
arr_2d[1]

array([4, 5, 6])

In [47]:
# Getting individual element value
arr_2d[1][0]

4

In [48]:
# Getting individual element value
arr_2d[1,0]

4

In [49]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

## Selection

selection based off of comparison operators.

In [50]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [53]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations
## Arithmetic

In [56]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Universal Array Functions

In [62]:
#Taking Square Roots
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [63]:
#Calcualting exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [64]:
np.max(arr) #same as arr.max()

10

In [66]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

# Task for you 
Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [23]:
b1=np.random.randint(0, 80, 25)
b1

array([ 0, 58, 56, 63, 37, 64, 40,  5, 72, 11, 13, 20, 46, 42, 17, 17, 15,
       78, 10, 13, 36, 61, 30, 60, 49])

Create an array of all the even integers from 10 to 50

In [22]:
c1=np.arange(10, 51)
c1=c1[c1%2==0]
c1

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Pandas
Pandas is an important package for Data science

In [2]:
import numpy as np
import pandas as pd

### Creating a Series

You can convert a list,numpy array, or dictionary to a Series:

In [3]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array([10,20,30])


In [4]:
# using list
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
#using numpy arrays
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

## Using an Index

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information (works like a hash table or dictionary).

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [6]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan']) 
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [7]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan']) 
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [8]:
ser1['USA']

1

In [9]:
# Operations can be performed based on Index 
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

## DataFrames 
Let's make dataframes 

In [10]:
import pandas as pd

In [11]:
a = np.random.rand(4,4)
Index = 'A B C D'.split()
Column = 'W X Y Z'.split()

In [90]:
df = pd.DataFrame(a, index= Index, columns=Column)
df

W         X         Y         Z
A  0.014824  0.564327  0.606248  0.470297
B  0.586563  0.166849  0.733254  0.868406
C  0.013971  0.414100  0.691070  0.891432
D  0.826677  0.421621  0.672397  0.460906

## Selection and Indexing

In [91]:
df['W']

A    0.014824
B    0.586563
C    0.013971
D    0.826677
Name: W, dtype: float64

In [92]:
# Pass a list of column names
df[['W','Z']]

W         Z
A  0.014824  0.470297
B  0.586563  0.868406
C  0.013971  0.891432
D  0.826677  0.460906

In [93]:
df.W

A    0.014824
B    0.586563
C    0.013971
D    0.826677
Name: W, dtype: float64

### Creating a new column

In [94]:
df['new'] = df['W'] + df['Y']

In [95]:
df

W         X         Y         Z       new
A  0.014824  0.564327  0.606248  0.470297  0.621073
B  0.586563  0.166849  0.733254  0.868406  1.319817
C  0.013971  0.414100  0.691070  0.891432  0.705041
D  0.826677  0.421621  0.672397  0.460906  1.499074

In [96]:
# removing columns 
df.drop('new',axis=1)

W         X         Y         Z
A  0.014824  0.564327  0.606248  0.470297
B  0.586563  0.166849  0.733254  0.868406
C  0.013971  0.414100  0.691070  0.891432
D  0.826677  0.421621  0.672397  0.460906

In [97]:
# Not inplace unless specified!
df

W         X         Y         Z       new
A  0.014824  0.564327  0.606248  0.470297  0.621073
B  0.586563  0.166849  0.733254  0.868406  1.319817
C  0.013971  0.414100  0.691070  0.891432  0.705041
D  0.826677  0.421621  0.672397  0.460906  1.499074

you can see that 'new'column is still there, in order to remove it permanently use inplace command

In [98]:
df.drop('new',axis=1,inplace=True)

In [99]:
df

W         X         Y         Z
A  0.014824  0.564327  0.606248  0.470297
B  0.586563  0.166849  0.733254  0.868406
C  0.013971  0.414100  0.691070  0.891432
D  0.826677  0.421621  0.672397  0.460906

** Selecting Rows**

In [100]:
df.loc['A']

W    0.014824
X    0.564327
Y    0.606248
Z    0.470297
Name: A, dtype: float64

### CSV
#### CSV Input

In [101]:
df = pd.read_csv('example')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

#### CSV Output

In [103]:
df.to_csv('example',index=False)

# Task for you
Generate a random number 4x4 matrix with numpy

Store the matrix in pandas dataframe 

Save it in a CSV

In [29]:
arr=np.random.rand(4, 4)
col="Aziz Mike Hassan Nizamul".split()
row="Program Science Maths Chemistry".split()
df_me = pd.DataFrame(arr, index= row, columns=col)

In [30]:
df_me

Aziz      Mike    Hassan   Nizamul
Program    0.617727  0.796029  0.118015  0.517066
Science    0.542109  0.589134  0.768076  0.594961
Maths      0.851372  0.454787  0.757623  0.269424
Chemistry  0.862125  0.892127  0.676994  0.979753

In [31]:
df_me.to_csv("name_mat.csv")